### ISSUE TITLE
have a problem with getenv()

### ISSUE THREAD

**Issue by NightsongGr** [SociallyIneptWeeb/LanguageLeapAI#12]
problem: line 9, in <module> BASE_URL = getenv('WHISPER_BASE_URL') 

TypeError: 'str' object is not collable

Code:

1)from os import getenv
2)from pathlib import Path
3)
4)import requests
5)from dotenv import load_dotenv
6)
7)load_dotenv()
8)
9)BASE_URL = getenv('WHISPER_BASE_URL')

**Comment by 0Xiaohei0** [comment]
Did you put quotations around your url?
I should look like this: 
![image](https://user-images.githubusercontent.com/24196833/224413463-a08f763d-0ee8-45b4-867f-780a3459f6cf.png)

**Comment by NightsongGr** [comment]
> 

I didnt put the json files only the .py and my urls wouldnt come up at all, thanks for letting me know
