### ISSUE TITLE
voice_translatior.py auto termination 

### ISSUE THREAD

**Issue by BLINK-SG** [SociallyIneptWeeb/LanguageLeapAI#13]
please please use google translator api im from IN I cant access DeepL api keys 😢 !!

**Comment by OrlandoMaya** [comment]
Let me try to find a solution with google translator API.

**Comment by OrlandoMR** [comment]
Let me try to find a solution with google translator.

**Comment by BLINK-SG** [comment]
Thanks man i tried it 
im not getting any errors in my terminal and the collab notebooks too 
still not able to get any output

**Comment by SociallyIneptWeeb** [comment]
I have added in an option to use Google Translate instead in the .env file in a new [commit](https://github.com/SociallyIneptWeeb/LanguageLeapAI/commit/bc6ea816e6dc18062dc492fcc4961fea36d587ba), so test to see if it works! 

As for your other issue, do wait for my setup video to ensure that you've set everything up properly :)

**Comment by BLINK-SG** [comment]
I tried the new commit i found that the code terminates itself without sending request to whisper
![image](https://user-images.githubusercontent.com/91750731/224471800-ba9e2ccd-dc54-43e0-bd77-618bec91e5b4.png)
