### ISSUE TITLE
Docker only works with a NVIDIA GPU

### ISSUE THREAD

**Issue by OrlandoMaya** [SociallyIneptWeeb/LanguageLeapAI#14]

**Comment by 0Xiaohei0** [comment]
A GPU shouldn't be needed at all for docker to run. 
Running this in the console should start voicevox using only your cpu: 
```
docker pull voicevox/voicevox_engine:cpu-ubuntu20.04-latest
docker run --rm -it -p '127.0.0.1:50021:50021' voicevox/voicevox_engine:cpu-ubuntu20.04-latest
```
The command is from [voicevox docker hub](https://hub.docker.com/r/voicevox/voicevox_engine)

**Comment by SociallyIneptWeeb** [comment]
You can but it's really slow. Also this uses up your CPU resources instead which will slow down your computer even more. Anyways there's a way to run it using Google colab
