### ISSUE TITLE
Problem when I execute voice_translator.py

### ISSUE THREAD

**Issue by HoloShiraha** [SociallyIneptWeeb/LanguageLeapAI#15]
![image](https://user-images.githubusercontent.com/87045765/224439670-9d645581-15c0-4777-8dc4-96e52d894f12.png)
![image](https://user-images.githubusercontent.com/87045765/224440034-f2bf8fbf-8ade-4909-aa99-172d1f1ff343.png)

**Comment by HoloShiraha** [comment]
![image](https://user-images.githubusercontent.com/87045765/224440635-3faa5800-7719-4f01-8ed8-7050ed87988a.png)

**Comment by 0Xiaohei0** [comment]
Are you running the program with src/voice_translator.py ?
You need to do run the commands in src folder as stated in usage:
![image](https://user-images.githubusercontent.com/24196833/224440544-49dd501a-b6da-4cf8-91db-3a70ec669014.png)

**Comment by BLINK-SG** [comment]
> Are you running the program with src/voice_translator.py ? You need to do run the commands in src folder as stated in usage: ![image](https://user-images.githubusercontent.com/24196833/224440544-49dd501a-b6da-4cf8-91db-3a70ec669014.png)

same error for me ( was running in src folder )

**Comment by 0Xiaohei0** [comment]
It is failing to find this file:
![image](https://user-images.githubusercontent.com/24196833/224440924-06f9e4be-cfb3-4886-951e-330f1d53e7ac.png)

**Comment by BLINK-SG** [comment]
i somehow fixed mines but i ave new error or something idk check it once 
https://github.com/SociallyIneptWeeb/LanguageLeapAI/issues/13#issuecomment-1464556413

**Comment by HoloShiraha** [comment]
I have to double click on this ?
![image](https://user-images.githubusercontent.com/87045765/224441045-80f6193b-3d34-4980-9186-a1e20ec2779d.png)
file

**Comment by 0Xiaohei0** [comment]
> I have to double click on this ? ![image](https://user-images.githubusercontent.com/87045765/224441045-80f6193b-3d34-4980-9186-a1e20ec2779d.png) file

Your can right click in file explorer, click open in terminal and type 
```
python voice_translator.py
```
![image](https://user-images.githubusercontent.com/24196833/224441642-e403edf9-c227-4c23-b942-14002ba923ed.png)
![image](https://user-images.githubusercontent.com/24196833/224441582-c1402446-2852-4fd4-801d-92a4660a6629.png)

**Comment by HoloShiraha** [comment]
Unfortunately, I'm on windows 10 :'(

**Comment by 0Xiaohei0** [comment]
> Unfortunately, I'm on windows 10 :'(

You should be able to do this on windows 10

**Comment by HoloShiraha** [comment]
![Capture](https://user-images.githubusercontent.com/87045765/224444537-3058d08b-f1c3-4dd8-9a50-05414321143f.PNG)

**Comment by 0Xiaohei0** [comment]
Try setting TARGET_LANGUAGE_CODE=ja in .env file

![image](https://user-images.githubusercontent.com/24196833/224444789-19c2641d-1581-47ba-b746-7929fd461b37.png)

**Comment by OrlandoMR** [comment]
I'm doing test and is basically problem in the post request, i'm trying to change localtunnel for ngrok but isn't working too

**Comment by HoloShiraha** [comment]
It's working but : No speech detected.
No speech detected.
No speech detected.
English: Flickner
Japanese: リペアラー

**Comment by HoloShiraha** [comment]
It doesn't like my accent x)

**Comment by 0Xiaohei0** [comment]
You can try running voicevox locally, I can't get voicevox to work on google colab either. see this issue #9

**Comment by HoloShiraha** [comment]
I've checked if I was able to download Docker but I can't enable Hyper-V :(

**Comment by SociallyIneptWeeb** [comment]
The google colab files has been updated so you can run these on the cloud if you are unable to install docker
