### ISSUE TITLE
Error while executing subtitler.py

### ISSUE THREAD

**Issue by BLINK-SG** [SociallyIneptWeeb/LanguageLeapAI#17]
Not sure about this error 
![image](https://user-images.githubusercontent.com/91750731/224444927-836034e6-8d7c-4143-872a-ac431f267776.png)
![image](https://user-images.githubusercontent.com/91750731/224444993-93aefcd7-8ddd-497f-94e8-86853755d117.png)

**Comment by SorenKyojin** [comment]
I got this
![image](https://user-images.githubusercontent.com/64634251/224446072-c28efd80-4606-482a-b1e6-9b7659d70982.png)
![image](https://user-images.githubusercontent.com/64634251/224446149-2d77724e-e1c8-4efc-b1ce-ae1ee7a59dd3.png)

And my audio devices:
![image](https://user-images.githubusercontent.com/64634251/224446547-da4c00e5-4d01-47ca-a320-c7ef54e4f1bc.png)
![image](https://user-images.githubusercontent.com/64634251/224446599-14f8d65f-aad6-40f3-b2d5-eeed0cf3ffec.png)

**Comment by SociallyIneptWeeb** [comment]
From the error messages, your whisper or voicevox docker containers may not be running.

**Comment by SorenKyojin** [comment]
> From the error messages, your whisper or voicevox docker containers may not be running.

I'll create another Issue, I have no more error but It does anything, I'll explain
