### ISSUE TITLE
DeepL Alternatives

### ISSUE THREAD

**Issue by kurosakijin** [SociallyIneptWeeb/LanguageLeapAI#18]
got any guide for this :D

**Comment by BLINK-SG** [comment]
You can try 

- https://pypi.org/project/googletrans/

**Comment by kurosakijin** [comment]
how do you use it?

**Comment by kurosakijin** [comment]
I mean code it :D

**Comment by SociallyIneptWeeb** [comment]
I have added in an option to use Google Translate instead in the .env file in a new [commit](https://github.com/SociallyIneptWeeb/LanguageLeapAI/commit/bc6ea816e6dc18062dc492fcc4961fea36d587ba), so test to see if it works!
