### ISSUE TITLE
japanese audio to english subs on live, can it be done?

### ISSUE THREAD

**Issue by SamuelXGMM** [SociallyIneptWeeb/LanguageLeapAI#19]
lets say if i were to play a japanese video on vlc or web browser and i need a way to send the audio to whisper so it can translate in in live not like and not like one mp3 auido after another but like in live i need to see english subs for an japanese audio instead of japanese i need english subs in my terminal or like you have discribed in your video and sorry for my bad english and i think it can be done but i dont know.

**Comment by SamuelXGMM** [comment]
if so how can anyone guide me?

**Comment by SociallyIneptWeeb** [comment]
You can set your web browser's audio output to voicemeeter's auxiliary cable input, then run subtitler which will display the eng subtitles on your screen. If you just want it as a transcript which constantly updates in your terminal, check out the [code](https://github.com/davabase/whisper_real_time) from davabase.

**Comment by SamuelXGMM** [comment]
oh thank you for the reply im on linux i can't use voicemeeter instead i can use pulsemeeter?

**Comment by SociallyIneptWeeb** [comment]
I'm not too familiar with it, but if it has similar functionalities with voicemeeter that may be possible.

**Comment by SamuelXGMM** [comment]
thanks, ill look into it.
