### ISSUE TITLE
DeepL alternatives?

### ISSUE THREAD

**Issue by hpacleb** [SociallyIneptWeeb/LanguageLeapAI#2]
I can't sign up for a free account due to being in an unsupported country so I was wondering if there are other alternatives?

**Comment by kurosakijin** [comment]
> 

do you have a code for that?

**Comment by SociallyIneptWeeb** [comment]
I have added in an option to use Google Translate instead in the .env file in a new [commit](https://github.com/SociallyIneptWeeb/LanguageLeapAI/commit/bc6ea816e6dc18062dc492fcc4961fea36d587ba), so test to see if it works!

As for your other issue, do wait for my setup video to ensure that you've set everything up properly :)
