### ISSUE TITLE
got an error when using subtitler.py

### ISSUE THREAD

**Issue by Skittleology** [SociallyIneptWeeb/LanguageLeapAI#20]
![image](https://user-images.githubusercontent.com/97757862/224454921-ffdac808-4e5b-4028-abba-fcdb4d9d71a5.png)

It worked fine before, I don't know what's going on.

**Comment by Skittleology** [comment]
i'm literally only using this to translate japanese sonic commercials and stuff

**Comment by SociallyIneptWeeb** [comment]
you might have to run it from the src folder as python subtitler.py

**Comment by Skittleology** [comment]
yep, works, thank you.
