### ISSUE TITLE
This openai WHISPER model has some serious problem 

### ISSUE THREAD

**Issue by schxar** [SociallyIneptWeeb/LanguageLeapAI#24]
![image](https://user-images.githubusercontent.com/65155656/224478133-472bb47b-07aa-482a-9e12-2225288e2c2e.png)
(ldo) G:\PRINT G0\LanguageLeapAI-main\LanguageLeapAI-main\src>python subtitler.py
Request timeout
Request timeout
Request timeout
Request timeout

not working at all

(ldo) G:\PRINT G0\LanguageLeapAI-main\LanguageLeapAI-main\src>python voice_translator.py
English: copy.
Japanese: をコピーします。
when i just said something complete not copy.

(ldo) G:\PRINT G0\LanguageLeapAI-main\LanguageLeapAI-main\src>python voice_translator.py
English: Thank you.
Japanese: ありがとうございます。
when i just say hey and it return thank you 

(ldo) G:\PRINT G0\LanguageLeapAI-main\LanguageLeapAI-main\src>python voice_translator.py
English: Are you?
Japanese: あなたはそうですか？
how are you return are you

and voice vox part just dont work at all ,colab tells me if i dont use voicevox clooud gpu just shut it down

**Comment by schxar** [comment]
Traceback (most recent call last):
  File "C:\Users\schxa\.conda\envs\ldo\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\schxa\.conda\envs\ldo\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\schxa\.conda\envs\ldo\lib\site-packages\keyboard\_generic.py", line 58, in process
    if self.pre_process_event(event):
  File "C:\Users\schxa\.conda\envs\ldo\lib\site-packages\keyboard\__init__.py", line 213, in pre_process_event
    key_hook(event)
  File "C:\Users\schxa\.conda\envs\ldo\lib\site-packages\keyboard\__init__.py", line 516, in <lambda>
    return hook_key(key, lambda e: e.event_type == KEY_DOWN or callback(e), suppress=suppress)
  File "voice_translator.py", line 74, in on_release_key
    speak(jp_speech, TARGET_LANGUAGE)
  File "G:\PRINT G0\LanguageLeapAI-main\LanguageLeapAI-main\src\modules\tts.py", line 8, in speak
    speak_jp(sentence)
  File "G:\PRINT G0\LanguageLeapAI-main\LanguageLeapAI-main\src\modules\voicevox.py", line 38, in speak_jp
    voicevox_query = r.json()
  File "C:\Users\schxa\.conda\envs\ldo\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\schxa\.conda\envs\ldo\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\schxa\.conda\envs\ldo\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\schxa\.conda\envs\ldo\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

maybe this is the problem for not working voicevox 
![image](https://user-images.githubusercontent.com/65155656/224478706-4fc3d5a4-b096-4a23-a2f1-7a042c5a46f2.png)

**Comment by schxar** [comment]
if my audio setting is wrong i will still get voicevox cloud server output logs for me 
![image](https://user-images.githubusercontent.com/65155656/224478769-e17b3dec-f3ac-4b8a-952a-1cda85fe89d8.png)

**Comment by SociallyIneptWeeb** [comment]
That error usually shows up if it's unable to connect to voicevox. I fixed a bug in the voicevox Colab file recently, so you might have to update it

**Comment by schxar** [comment]
> That error usually shows up if it's unable to connect to voicevox. I fixed a bug in the voicevox Colab file recently, so you might have to update it

thanks,i will update the colab file and try again

**Comment by BLINK-SG** [comment]
Everything works fine for me but the response has like 6-7 sec delay

**Comment by hoangvu12** [comment]
> Everything works fine for me but the response has like 6-7 sec delay

If you can run the voicevox and whisper on your machine, you should do it. Run them on the cloud will add delay the translation.

**Comment by BLINK-SG** [comment]
> > Everything works fine for me but the response has like 6-7 sec delay
> 
> If you can run the voicevox and whisper on your machine, you should do it. Run them on the cloud will add delay to the translation process.

my gpu aint capable of processing it got 2gb vram

**Comment by SociallyIneptWeeb** [comment]
If you run both on the cloud, you will just face a slightly longer delay since your speech audio first has to be sent to the whisper cloud instance, whisper transcribes it and returns the english text response, deepl translates it, and more requests made to voicevox to generate the TTS audio file before sending it to your PC and the program playing it.
