### ISSUE TITLE
VoiceVox voice ID

### ISSUE THREAD

**Issue by kurosakijin** [SociallyIneptWeeb/LanguageLeapAI#26]
where did you get those?

**Comment by SociallyIneptWeeb** [comment]
If you have voicevox running, go to the base URL/docs. Eg  http://localhost:50021/docs. Then scroll down to GET /speakers, click try it out, execute, then in the response you should be able to see all the IDs and the names of the voices. You can refer to the voicevox official website to see which name corresponds to what voice sample

**Comment by kurosakijin** [comment]
I did but this happened
![image](https://user-images.githubusercontent.com/84918504/224486128-6a9892b4-854a-45d9-ab16-b65cc18907d6.png)
