### ISSUE TITLE
Google colab

### ISSUE THREAD

**Issue by OrlandoMR** [SociallyIneptWeeb/LanguageLeapAI#29]
Okay now is working the "server" created at google colab, but is returning me a 500 request error:

![imagen](https://user-images.githubusercontent.com/73142446/224488008-a8388d4c-43c0-46e2-b41f-b8d5b3da270c.png)

Do you think there is an error when im not using the colab GPU?

**Comment by SociallyIneptWeeb** [comment]
I think you may have to check your VOICEVOX_BASE_URL and update it to use the public URL that is displayed in Colab. Then restart your python program. If this still doesn't work, you may have to check if your firewall is blocking requests to the public IP address

**Comment by OrlandoMR** [comment]
Okay i fixed and also i change the localtunnel to ngrok, basically is necessary run the colab with gpu for the voicevox file.
