### ISSUE TITLE
TypeError on line 10 of src\modules\asr.py

### ISSUE THREAD

**Issue by NekomimiGaDaisuki** [SociallyIneptWeeb/LanguageLeapAI#31]
![Screenshot 2023-03-11 205231](https://user-images.githubusercontent.com/127547082/224488542-5dbabd71-45f1-4f89-b1f4-156cb0264fdd.jpg)

**Comment by hoangvu12** [comment]
> ![Screenshot 2023-03-11 205231](https://user-images.githubusercontent.com/127547082/224488542-5dbabd71-45f1-4f89-b1f4-156cb0264fdd.jpg)
> 

Hey, check your .env file, or the directory you are running the file.

Notice that you must cd to /Project/src and run the script in order to make it works.

**Comment by NekomimiGaDaisuki** [comment]
First, Chào ông.
Second, my bad, i just made change to .env.sample file instead of make an .env file. Yeah... i'm not too smart T_T
