### ISSUE TITLE
DeepL

### ISSUE THREAD

**Issue by noonsa-g** [SociallyIneptWeeb/LanguageLeapAI#32]
i just want use subtitler do I still need to use DeepL?
because DeepL doesnt support my country cart

**Comment by hoangvu12** [comment]
> i just want use subtitler do I still need to use DeepL?
> because DeepL doesnt support my country cart
You don't need it since
 you can use Google Translate instead.

**Comment by noonsa-g** [comment]
how?

**Comment by 0Xiaohei0** [comment]
I'm pretty sure subtitler does not use deepl, it uses whisper translate to output an English script.

**Comment by hoangvu12** [comment]
> I'm pretty sure subtitler does not use deepl, it uses whisper translate to output an English script.

Huh? I thought Whisper is being used for Speech to text?

**Comment by 0Xiaohei0** [comment]
![image](https://user-images.githubusercontent.com/24196833/224488934-72762582-8e8b-41e0-a54a-a21b541af0e5.png)
From whisper api doc

**Comment by hoangvu12** [comment]
> ![image](https://user-images.githubusercontent.com/24196833/224488934-72762582-8e8b-41e0-a54a-a21b541af0e5.png)
> From whisper api doc

I see? So it can only translate non-English to English?

**Comment by 0Xiaohei0** [comment]
![image](https://user-images.githubusercontent.com/24196833/224489067-db88088c-9bd7-45cb-bb65-cf294b2de511.png)
If you follow the call stack from subtitler you eventually end up in this translate function that calls whisper.

**Comment by SociallyIneptWeeb** [comment]
Whisper is capable of translating non eng speech to English text. That is what I'm using for the subtitler. So yes, if you only want to use the subtitler, you do not need deepl
