### ISSUE TITLE
WinError 10061

### ISSUE THREAD

**Issue by noonsa-g** [SociallyIneptWeeb/LanguageLeapAI#36]
![resim](https://user-images.githubusercontent.com/35300229/224491502-204b6ef1-b0a3-4562-94be-2473e7488f68.png)
how i can fix this

**Comment by SociallyIneptWeeb** [comment]
Usually this means the python program is unable to connect to whisper. Check if whisper is running in the docker container, or in the Google cloud notebook. Then check if your WHISPER_BASE_URL is updated to the correct URL.

**Comment by noonsa-g** [comment]
where i find my ngrok url

**Comment by SociallyIneptWeeb** [comment]
It will show up after the run all the cells in the Colab notebook
