### ISSUE TITLE
Application limitations

### ISSUE THREAD

**Issue by 0Xiaohei0** [SociallyIneptWeeb/LanguageLeapAI#37]
Reguarding this: 
> ### Application limitations
> Some applications like Valorant for some reason does not allow open mic for team voice chat, so LanguageLeapAI will not work for in these cases, unless you hold down the push to talk button whenever you want your teammates to hear the Text-to-Speech. However, Valorant does have open mic for party voice-chat, so there should be no issue if it's used towards your party members.

We could hold down the push to talk button through code while the audio is playing. The keyboard module already imported should be able to do this (https://github.com/boppreh/keyboard#keyboardpresshotkey)

**Comment by SociallyIneptWeeb** [comment]
Yup but that's just so scuffed, having to time and hold down that separate key just to play it to your team voice chat. I would imagine it would just be a pain to use it that way.

**Comment by 0Xiaohei0** [comment]
Something like this should work:
![image](https://user-images.githubusercontent.com/24196833/224493770-ea879295-4647-444b-9439-121ce0aad2f7.png)
All the user need to do is specify the push-to-talk key.
> Unless you are suggesting we programmically hold down that push to talk key the entire time our application is running

This should work as well.

**Comment by SociallyIneptWeeb** [comment]
Hmm now that I think about it it's not that bad, however most apps like disc, apex don't really have to worry about this problem so this is kinda an edge case, maybe I'll add this feature in later on, unless someone else does it first.

**Comment by 0Xiaohei0** [comment]
I'll work on this.
