### ISSUE TITLE
can't run the python programs

### ISSUE THREAD

**Issue by FocaNTG** [SociallyIneptWeeb/LanguageLeapAI#42]
![image](https://user-images.githubusercontent.com/69857862/224513934-7b476fa7-c2c4-48ef-bf77-1ca1523b893c.png)

**Comment by 0Xiaohei0** [comment]
Did you fill out your .env file? Seems like the value of REQUEST_TIMEOUT is None

**Comment by teteterence2** [comment]
I got the same issue too even there is value for REQUEST_TIMEOUT
![env sample - Notepad 3_12_2023 1_13_31 PM](https://user-images.githubusercontent.com/127607084/224525773-5831198a-94ef-4e4b-93a6-fce0867536c9.png)

**Comment by SociallyIneptWeeb** [comment]
Please copy .env.sample to .env based on the instructions in the [docs](docs/ENV.md) .

**Comment by FocaNTG** [comment]
> Did you fill out your .env file? Seems like the value of REQUEST_TIMEOUT is None

basically i did the cp .env.sample thing but im on windows and it took me like 3 hours to realise that was an invalid command even tho it was telling me that the whole time

**Comment by SociallyIneptWeeb** [comment]
Oh you can do it in power shell terminal as well and it would work

**Comment by FocaNTG** [comment]
![image](https://user-images.githubusercontent.com/69857862/224533199-568349ba-73b8-48a8-a008-eb9646a5674a.png)
now im having this error when running subtitler, running voice translator it says nothing for like a few minutes then says "No audio file to transcribe detected." but that doesnt sound as bad

**Comment by SociallyIneptWeeb** [comment]
I'm guessing the subtitler is unable to connect to your audio device output. You may have to ensure you have entered the correct audio device id in your .env file.

**Comment by FocaNTG** [comment]
i redid the device config but subtitler gives the same error, voice translator translates my text right but then it gives this error
![image](https://user-images.githubusercontent.com/69857862/224536592-87623617-9681-4a19-8610-7359d1c17cab.png)

**Comment by SociallyIneptWeeb** [comment]
It looks like the program cannot connect to your vac cable input device. You may have to ensure that your virtual audio cable is properly installed or the id for your vac cable input or speakers in the .env file is correct.

**Comment by FocaNTG** [comment]
im going insane :3

**Comment by FocaNTG** [comment]
it worked for a sec but only in my headphones, now after reinstalling virtual cables and rewriting the ids for the 69th time i think i made it worse

**Comment by FocaNTG** [comment]
![image](https://user-images.githubusercontent.com/69857862/224545425-001b12d8-0faa-4077-9945-8bf69800aa34.png)
![image](https://user-images.githubusercontent.com/69857862/224545444-e8a01ea5-d95c-4220-a1db-f1c954319cf3.png)
is this right?

**Comment by SociallyIneptWeeb** [comment]
I can confirm that all of them are right, except maybe your microphone, but I'm assuming you selected it correctly as well and you aren't using a microphone called screaming bee audio/Microsoft lifecam/Iriun Webcam

**Comment by FocaNTG** [comment]
subtitler works, but im not sure how to use it

**Comment by SociallyIneptWeeb** [comment]
It will translate any audio played into the auxiliary cable to English and display it on screen. So all you have to do is run the code, then set the audio output of the app that you want the audio translated to be set to Auxillary cable input

**Comment by FocaNTG** [comment]
ty
