### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by Zxen-byte** [SociallyIneptWeeb/LanguageLeapAI#43]
Umm, I already installed the requirements.txt and also fill the .env file already done in google colab but I'm still getting an error
![image-1](https://user-images.githubusercontent.com/80733641/224520042-2de282a2-0ec3-423c-8705-151e561fe1ad.png)

**Comment by SociallyIneptWeeb** [comment]
Ensure that your .env file is filled in correctly
