### ISSUE TITLE
Voice sounds incredibly robotic

### ISSUE THREAD

**Issue by QuiteAFancyEmerald** [SociallyIneptWeeb/LanguageLeapAI#44]
Hello,

I was just curious on if you had a potential fix for preventing this from sounding incredibly robotic. I had resorted to tweaking the settings below but for whatever reason it clips at points (despite having a good mic although I don't think this is the reason) and just sounds off compared to your initial video.

```js
VOICE_ID=20

# Type: float
SPEED_SCALE=1.0
VOLUME_SCALE=3.0
INTONATION_SCALE=1.5
PRE_PHONEME_LENGTH=1.0
POST_PHONEME_LENGTH=1.0
```

**Comment by SociallyIneptWeeb** [comment]
I'm not sure what you mean by clips, but if it sounds robotic maybe you can try different voices, also the quality of your mic doesn't matter as the TTS voice is simply being played into your speakers and into the vac cable

**Comment by QuiteAFancyEmerald** [comment]
I could send an example of what I mean by "clipping" but I'll try that. I just am curious how the same voice sounds so much better in your video or if maybe the settings above are not optimal?

https://cdn.discordapp.com/attachments/667692213022752769/1084311838281441280/ai_moments.mp4

**Comment by SociallyIneptWeeb** [comment]
From the sounds of it, it just sounds a bit fast, so you just have to use a speed scale of like 0.8 or something. Also idk why there are error messages appearing even tho the voice is properly being played

**Comment by QuiteAFancyEmerald** [comment]
Yeah its all good. Lowering the speed seemed to help. As for the errors no clue. I am using Google Collab with the proper environmental settings and have python 3.10.10 installed. Perhaps this is just a Google Collab thing since I have yet to try out Docker locally.
