### ISSUE TITLE
Unable to reach whisper

### ISSUE THREAD

**Issue by Zxen-byte** [SociallyIneptWeeb/LanguageLeapAI#46]
I'm getting a problem while running the voice_translator it says
![image](https://user-images.githubusercontent.com/80733641/224526291-918c8d05-3700-46b4-b81f-6e293f2e7fc2.png)
even though the variables are correct ig.
![image](https://user-images.githubusercontent.com/80733641/224526411-61c32284-78a3-4a99-9f5f-b915b8a39b2d.png)
![image](https://user-images.githubusercontent.com/80733641/224526442-eb345298-c2e5-4c9b-8023-19d368d98206.png)
![image](https://user-images.githubusercontent.com/80733641/224526485-13cede94-c3d4-4668-9010-e83889b3f267.png)

**Comment by SociallyIneptWeeb** [comment]
You might have to check whether your firewall is blocking requests from Whisper's public IP address provided by ngrok

**Comment by Zxen-byte** [comment]
> You might have to check whether your firewall is blocking requests from Whisper's public IP address provided by ngrok

Sorry but how to do that. I have less knowledge in firewall since I'm not messing with it

**Comment by jamhea23** [comment]
bro we got the same issue. haven't found a solution yet :((

**Comment by SociallyIneptWeeb** [comment]
Maybe you can try disabling your firewall for a while just to test if it's really a firewall issue. If you are able to connect to Whisper after disabling the firewall, then that confirms that the firewall is blocking requests from the public IP address, and you will have to probably google and find a way to configure your firewall to allow that public IP address.

**Comment by frrrrrits** [comment]
could you check the response code when getting a requests to whisper, in my case it couldn't connect because i was using vpn, so i had to set the proxy manually.

_[Refering to this](https://github.com/SociallyIneptWeeb/LanguageLeapAI/blob/74934ff73a455730424abf4c1ce8ee0574a23f25/src/modules/asr.py#L36C4-L38)_ 
`print(f"response code: {response.status_code}")`

**Comment by jamhea23** [comment]
@Zxen-byte how'd u fix it bro?

**Comment by Zxen-byte** [comment]
> @Zxen-byte how'd u fix it bro?

well i was using mobile data that time but when i use my internet it got fixed

**Comment by jamhea23** [comment]
> 

thanks
