### ISSUE TITLE
discord not detecting audio

### ISSUE THREAD

**Issue by BenotVT** [SociallyIneptWeeb/LanguageLeapAI#48]
I have all the program well configured but discord and obs do not detect the sound through the cable output

![image](https://user-images.githubusercontent.com/127665056/224542755-efe9b732-7f1f-46dc-975f-a8d28d9a0c64.png)

![image](https://user-images.githubusercontent.com/127665056/224542797-2e7a82b9-7e1e-4308-a6db-b179c44794cc.png)

**Comment by BenotVT** [comment]
Solved

**Comment by SociallyIneptWeeb** [comment]
Nice!
