### ISSUE TITLE
whisper return {"detail":"Not Found"}

### ISSUE THREAD

**Issue by artist012** [SociallyIneptWeeb/LanguageLeapAI#49]
As written in the title, the response of the request to '{BASE_URL}/asr?task=transcribe&language=en&output=json' in transcribe() is {"detail":"Not Found"}, is there a solution?

Additionally, when the transcribe() function ends, the program terminates. Is it possible to prevent it?

I don't even know why this is

**Comment by hughes012** [comment]
I used a translator because I'm not good at English, so please forgive me if it's weird

**Comment by SociallyIneptWeeb** [comment]
Are you running whisper in a docker container or using Google colab notebook?

**Comment by bpvallespin** [comment]
Encountered the same error {"detail":"Not Found"}. I was using Google Colab.

Also, encountered this error.

![image](https://user-images.githubusercontent.com/127683094/224559941-6d9efba5-7410-4fe4-a523-e31957ca9937.png)

**Comment by hughes012** [comment]
> Are you running whisper in a docker container or using Google colab notebook?

docker

**Comment by SociallyIneptWeeb** [comment]
> Encountered the same error {"detail":"Not Found"}. I was using Google Colab.
> 
> Also, encountered this error.
> 
> ![image](https://user-images.githubusercontent.com/127683094/224559941-6d9efba5-7410-4fe4-a523-e31957ca9937.png)
> 
> Thanks in advance for your help!

This is for the voicevox Colab, and you can ignore the warnings, voicevox will still work

**Comment by SociallyIneptWeeb** [comment]
> > Are you running whisper in a docker container or using Google colab notebook?
> 
> docker

Can you check if your docker container is running? You can do so by navigating to {BASE_URL}/docs and see if you can see the documentation page for Whisper's api

**Comment by hughes012** [comment]
> 

yes

> > > Are you running whisper in a docker container or using Google colab notebook?
> > 
> > 
> > docker
> 
> Can you check if your docker container is running? You can do so by navigating to {BASE_URL}/docs and see if you can see the documentation page for Whisper's api

it's working normally

**Comment by hughes012** [comment]
> > > Are you running whisper in a docker container or using Google colab notebook?
> > 
> > 
> > docker
> 
> Can you check if your docker container is running? You can do so by navigating to {BASE_URL}/docs and see if you can see the documentation page for Whisper's api

I can see the documentation page for whisper api

**Comment by SociallyIneptWeeb** [comment]
Can you try running asr.py in the src/modules folder?

**Comment by hughes012** [comment]
> Can you try running asr.py in the src/modules folder?

![image](https://user-images.githubusercontent.com/84890747/224697209-8d1e4987-94c9-44c6-8e60-5a1852f2da21.png)

**Comment by hughes012** [comment]
> > > Can you try running asr.py in the src/modules folder?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/84890747/224697209-8d1e4987-94c9-44c6-8e60-5a1852f2da21.png)
> > ![image](https://user-images.githubusercontent.com/84890747/224698448-8a939193-a638-4b72-acfc-2e4b920d9d29.png)
> 
> maybe the response not returning anything, thats why error on `Text`. "text" is not somewhere on the response in this case it's should be (json) or response is not json (invalid) or Null. you can debug it like this `print(r.text)` on top of `try` "r" is the requests, to see what actually the response is (that's all as far i know because im not using docker).

The result is {"detail":"Not Found"}

**Comment by SociallyIneptWeeb** [comment]
Lol I'm clueless. You can see the API documentation page which means whisper is running, but when you actually make an API request it returns not found
