### ISSUE TITLE
How to set this up?

### ISSUE THREAD

**Issue by da3dsoul1** [SociallyIneptWeeb/LanguageLeapAI#5]
Can someone please do a step-by-step guide? I just wanna use the voice talk option, I can't seem to figure out what to do with pip and cp commands, also what do I do with docker, it's so confusing.

**Comment by SociallyIneptWeeb** [comment]
I'll make a video soon for how to set it up :)

**Comment by da3dsoul1** [comment]
Thank you so much, will be waiting

**Comment by da3dsoul1** [comment]
So I managed to do this, but it doesn't do anything for me when playing japanese files, or holding down the hotkey button. Perhaps the problem lies in the sound IDs?
![image](https://user-images.githubusercontent.com/111184581/224361232-32fc0a94-8139-42e5-b29b-a792b7ef3a3c.png)

**Comment by SociallyIneptWeeb** [comment]
I think you have to run the python files, running docker compose only starts the whisper and Voicevox services.

**Comment by da3dsoul1** [comment]
![image](https://user-images.githubusercontent.com/111184581/224362426-0a8784db-7a29-42bc-9778-1ec3eb10de67.png)
I got errors trying to run them.

**Comment by SociallyIneptWeeb** [comment]
Check if your .env file is properly filled up with the right variable values.

**Comment by da3dsoul1** [comment]
> Check if your .env file is properly filled up with the right variable values.

AUDIO DEVICE IDS?

**Comment by da3dsoul1** [comment]
I'm not really sure which to pick
![image](https://user-images.githubusercontent.com/111184581/224363621-d3093345-7d6e-41d5-bb8f-e7126145cd12.png)
Previously I've slelected these
![image](https://user-images.githubusercontent.com/111184581/224363770-5a134f7f-2712-437a-bc2b-b6364c4470d1.png)

**Comment by SociallyIneptWeeb** [comment]
I think your mic id should be 1 or 12, not 13. I believe mic game 1 is your mic

**Comment by 0Xiaohei0** [comment]
I made a similar project inspired by @SociallyIneptWeeb 's initial video. I decided to host everything on Microsoft Azure so that you can run the project with zero setup. You can check out the project here: (https://github.com/0Xiaohei0/VoiceToJapanese)

**Comment by zbmwE46** [comment]
![image](https://user-images.githubusercontent.com/127540646/224385555-56e4fb9f-7b4d-4f47-9fab-f5384d34f308.png)
im kinda lost here, which root folder?

**Comment by da3dsoul1** [comment]
> ![image](https://user-images.githubusercontent.com/127540646/224385555-56e4fb9f-7b4d-4f47-9fab-f5384d34f308.png) im kinda lost here, which root folder?

I was the same, it's the downloaded folder LanguageLeapAI-main, open cmd there and type pip install -r requirements.txt



> I made a similar project inspired by @SociallyIneptWeeb 's initial video. I decided to host everything on Microsoft Azure so that you can run the project with zero setup. You can check out the project here: (https://github.com/0Xiaohei0/VoiceToJapanese)

Thank you so much for this, it's so easy and just works! Though I don't know how to make it the output sound, is it possible?

**Comment by 0Xiaohei0** [comment]
I'm currently using a virtual audio cable to connect the voice output to other programs(see tutorial here: https://youtu.be/4sGWzOyF82M).
