### ISSUE TITLE
How do I get voice IDs?

### ISSUE THREAD

**Issue by jechosu** [SociallyIneptWeeb/LanguageLeapAI#50]
I have a question, if I want to change the voice to a male voice, how do I get the voice IDs to obtain the voice I want for the value `VOICE_ID` in the .env?

**Comment by SociallyIneptWeeb** [comment]
Make a get request to {VOICEVOX_BASEURL}/speakers and you will receive a JSON response with all the names of the voices and their IDs. Then you can check out the official voicevox website which has all the names and voice samples.

**Comment by jechosu** [comment]
alright, thanks!
