### ISSUE TITLE
Auto Translator auto stopping after I say anything

### ISSUE THREAD

**Issue by SrijanSharma21** [SociallyIneptWeeb/LanguageLeapAI#56]

**Comment by SrijanSharma21** [comment]
I got it to work but now nothing happens when I hold "F" and talk

**Comment by frrrrrits** [comment]
please give some detail log error msg or something.

**Comment by SrijanSharma21** [comment]
it gave no error msg or logs when I press F and speak and release the F key it just stops the process but in the Whisper AI logs it gives the 400 bad request error

**Comment by SrijanSharma21** [comment]
![image](https://user-images.githubusercontent.com/89529598/224770137-a1f2f0a4-14fb-40ce-94fc-235fd6d131c8.png)

**Comment by frrrrrits** [comment]
probably something wrong with your connection, do you use vpn?

**Comment by SrijanSharma21** [comment]
no I do not use a vpn

**Comment by SrijanSharma21** [comment]
wait can you check if these audio ids or what ever are correct?

**Comment by frrrrrits** [comment]
@SrijanSharma21 if audio problem that requests to Whisper will not run, check the logs on the colab.

**Comment by SrijanSharma21** [comment]
![image](https://user-images.githubusercontent.com/89529598/224771963-b606dd10-7bdf-4907-a717-f9a041209869.png)
this is the only thing I get

**Comment by SrijanSharma21** [comment]
yes an http 400 request thing which I believe is the bad request one
