### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by SamuelXGMM** [SociallyIneptWeeb/LanguageLeapAI#58]
➜  ~ python3.8 subtitltler.py                        
Traceback (most recent call last):
  File "subtitltler.py", line 11, in <module>
    from modules.audio_translate import translate_audio
ModuleNotFoundError: No module named 'modules.audio_translate'; 'modules' is not a package

**Comment by SociallyIneptWeeb** [comment]
You might have to ensure in the modules folder, an empty __init__.py file is there. Also why is subtitler spelled like that lol

**Comment by SamuelXGMM** [comment]
wow i did not how i spelled subtitler until you told me now and what do you mean by that i just copied the subtitler.py code from github page and pasted it and used it so where is this modules folder i dont see one in the github page

**Comment by SociallyIneptWeeb** [comment]
Please follow the instructions in INSTALLTION.md in the docs folder

**Comment by frrrrrits** [comment]
bro, life gona be much easier if we use Ide Editor e.g vscode 💀

**Comment by SamuelXGMM** [comment]
i usually look for instructions but this time it seem harder but it could just be my bad eye sight but thanks again @SociallyIneptWeeb

**Comment by TravS419** [comment]
I get this when I try to run the voice translator 
![image](https://user-images.githubusercontent.com/60555741/225210682-01497544-f744-474a-a63c-75892eb3bf76.png)
And this when I run the subtitler
![image](https://user-images.githubusercontent.com/60555741/225210921-d838a43e-5f4a-4829-9187-f0d34656bb6d.png)

**Comment by SociallyIneptWeeb** [comment]
You might have to run the pip install  instructions under docs/INSTALLATION.md

**Comment by TravS419** [comment]
This fixed it thank you.
