### ISSUE TITLE
Discord link

### ISSUE THREAD

**Issue by YetiHug** [SociallyIneptWeeb/LanguageLeapAI#60]
https://discord.gg/atFZspcPtH

**Comment by SociallyIneptWeeb** [comment]
Can you send an invite link instead?

**Comment by YetiHug** [comment]
![screen](https://user-images.githubusercontent.com/118148513/225023472-5874b23d-7139-4bf5-b7f6-4e8c796c4a82.png)
https://discord.gg/AUh9XDrvqa

i mean, it should be working

**Comment by YetiHug** [comment]
my discord ign is yetihugs#6282 if it still doesn't work

**Comment by SociallyIneptWeeb** [comment]
Alright sick it works

**Comment by YetiHug** [comment]
btw is SociallyIneptWeeb#1673 ur account?

**Comment by SociallyIneptWeeb** [comment]
Yep thanks for being safe and checking!
