### ISSUE TITLE
ModuleNotFoundError: No module named 'googletrans' I'm trying to use googletranslate instead of deepl.

### ISSUE THREAD

**Issue by excursion0** [SociallyIneptWeeb/LanguageLeapAI#66]
the subtitler worked fine tho
![image](https://user-images.githubusercontent.com/127945059/225295878-03d2ee60-5ced-48d7-9dec-c41dfa6e7715.png)

**Comment by VeritasMagnus** [comment]
the subtitler worked fine tho

**Comment by SociallyIneptWeeb** [comment]
Maybe run the pip install -r requirements.txt again

**Comment by VeritasMagnus** [comment]
I found an error. Is this related?
![test](https://user-images.githubusercontent.com/127945059/225307086-f40788d4-a997-479a-8911-86bea3813863.png)
