### ISSUE TITLE
Can't open LangaugeLeapAI in cmd src / folder command

### ISSUE THREAD

**Issue by Oni222444** [SociallyIneptWeeb/LanguageLeapAI#69]
For some reason, this is happening when I open the cmd and run the command for src / folder.
I tried saving the .env file and closing Visual Studio Code, also I tried running cmd as admin.
Idk what it could be, here are some images so you can see what is happening.

https://imgur.com/a/oamEYhM
https://imgur.com/Cb3ltHR
https://imgur.com/QNrSieX

**Comment by SociallyIneptWeeb** [comment]
You might have to set your applications output device to be voicemeeter aux input

**Comment by Oni222444** [comment]
Ok I did this in my sound settings as well as VoiceMeeter Banana, and still does not load on the cmd command. Maybe restarting my computer?

https://imgur.com/tju9YmK
https://imgur.com/ZzASCvV
https://imgur.com/xFbgRuY
https://imgur.com/WDYNiet

**Comment by SociallyIneptWeeb** [comment]
For your default recording device in the control panel, just set it to your mic instead of aux
