### ISSUE TITLE
Voicemeter Setup

### ISSUE THREAD

**Issue by coolpersonnn** [SociallyIneptWeeb/LanguageLeapAI#7]
Before I try using this, I want to make sure that my voice meter is setup correctly before it potentially destroys my audio and bluescreens my pc
![image](https://user-images.githubusercontent.com/61058300/224355345-102db870-8b55-4de4-8301-e1e64405370b.png)

**Comment by SociallyIneptWeeb** [comment]
True, you can wait for my next video where I go into further details on the setup of everything :)

**Comment by coolpersonnn** [comment]
> True, you can wait for my next video where I go into further details on the setup of everything :)

i'm too excited to wait lol
im running the thingies on google colab and i've put the urls in my env file. im not sure whats next though. sorry if im being so bothersome
![image](https://user-images.githubusercontent.com/61058300/224360293-4dd2a083-85bc-4555-8a23-d80ee28a6e1b.png)

**Comment by 0Xiaohei0** [comment]
If you have set up everything correctly, you should try running the python script with:
```python src/voice_translator.py```

**Comment by coolpersonnn** [comment]
> If you have set up everything correctly, you should try running the python script with: `python src/voice_translator.py`

![image](https://user-images.githubusercontent.com/61058300/224363362-24abd93a-d8a0-45b5-93bb-45136cc53402.png)
not sure what happened there, the subtitles work pretty well though with some request timed out errors

**Comment by SociallyIneptWeeb** [comment]
You probably used the wrong IDs for the audio devices in the .env file, you might have to change those

**Comment by coolpersonnn** [comment]
> You probably used the wrong IDs for the audio devices in the .env file, you might have to change those

the only id i think could be wrong is the speakers
![image](https://user-images.githubusercontent.com/61058300/224370910-c832fab4-ce03-4d56-95b2-09e2ece5568c.png)
should it be the same a vm hardware out (speakers thx spatial audio)?

**Comment by coolpersonnn** [comment]
same error. however i just noticed this 
![image](https://user-images.githubusercontent.com/61058300/224373568-32cffc32-5dae-40cc-bea9-26baebf7b21c.png)
not sure what i need to change in my firewall

**Comment by 0Xiaohei0** [comment]
You can also try running voicevox on your local machine.

**Comment by coolpersonnn** [comment]
> You can also try running voicevox on your local machine.

again same issue. 
![image](https://user-images.githubusercontent.com/61058300/224378579-689ea946-8094-47c1-ba8d-34a7da330426.png)
error comes up when i press f

**Comment by 0Xiaohei0** [comment]
Try checking your microphone privacy settings and allow python to access your mic.

**Comment by coolpersonnn** [comment]
> Try checking your microphone privacy settings and allow python to access your mic.

it was on by deafult

**Comment by 0Xiaohei0** [comment]
https://stackoverflow.com/a/57086198 This seems to be the same error message. The answer suggests that your anti-virus blocked your python script call to the hardware level.

**Comment by coolpersonnn** [comment]
I only use windows defender but ill try turn it off and restart

**Comment by coolpersonnn** [comment]
> I only use windows defender but ill try turn it off and restart
nope that didnt work

**Comment by 0Xiaohei0** [comment]
I made a similar project that requires zero setup. You can see this issue for links #5

**Comment by coolpersonnn** [comment]
> Ref

Oh thank you this is great

**Comment by coolpersonnn** [comment]
> https://stackoverflow.com/a/57086198 This seems to be the same error message. The answer suggests that your anti-virus blocked your python script call to the hardware level.

is there a solution to this? i don't particularly want to remove windows defender from my system

**Comment by 0Xiaohei0** [comment]
> > https://stackoverflow.com/a/57086198 This seems to be the same error message. The answer suggests that your anti-virus blocked your python script call to the hardware level.
> 
> is there a solution to this? i don't particularly want to remove windows defender from my system

It's probably not a windows defender issue, I can run the project fine without disabling any security settings.
You can try running something like this: (https://stackoverflow.com/a/40157297)
If it works then python does have access to your mic.

**Comment by coolpersonnn** [comment]
> > > https://stackoverflow.com/a/57086198 This seems to be the same error message. The answer suggests that your anti-virus blocked your python script call to the hardware level.
> > 
> > 
> > is there a solution to this? i don't particularly want to remove windows defender from my system
> 
> It's probably not a windows defender issue, I can run the project fine without disabling any security settings. You can try running something like this: (https://stackoverflow.com/a/40157297) If it works then python does have access to your mic.

i changed something in the settings and i no longer have that issue. but i now get this error after holding f and speaking
![image](https://user-images.githubusercontent.com/61058300/224394306-249dd03b-e976-4c64-9b7c-f99186dca0ca.png)

**Comment by coolpersonnn** [comment]
I decided to setup VoiceMeter again using the steps in Audio Routing Documentation, however i now cant hear anything at all despite triple checking that i set the right playback devices and a1s and b2s and everything else.

**Comment by 0Xiaohei0** [comment]
Can you hear the synthesized audio without voicemeeter?
Here's how I set mine up:
![image](https://user-images.githubusercontent.com/24196833/224434652-6a12bf99-864d-42df-a1eb-e54fb028c5a7.png)
This should allow the script to output to both your game and your headphones.

**Comment by coolpersonnn** [comment]
Yours isnt the same as mine because it isnt the banana version
![image](https://user-images.githubusercontent.com/61058300/224435738-318d19da-4ba2-4df1-9916-e968b2ed45f4.png)
audio from my mic is working but nothing from my desktop, i can see the aux is clearly hearing the audio even though im supposed to set the vaio as my default playback device.

**Comment by hoangvu12** [comment]
> True, you can wait for my next video where I go into further details on the setup of everything :)

Can't wait to watch that video.

**Comment by SrijanSharma21** [comment]
hello i have a question on my Voicemeter I cant find the CABLE Input how do I fix this?

**Comment by SrijanSharma21** [comment]
I got it
