### ISSUE TITLE
How can i fix this?

### ISSUE THREAD

**Issue by Brawl-Master** [SociallyIneptWeeb/LanguageLeapAI#71]
I don't know what I'm doing wrong, I set up everything and still get this error.
![Screenshot 2023-03-16 214454](https://user-images.githubusercontent.com/127608152/225794728-042d0b15-75e5-4ec5-a97a-59a99fdde3d3.png)
![Screenshot 2023-03-16 205946](https://user-images.githubusercontent.com/127608152/225794753-c2d6184a-6b04-4036-ab77-73f8e53f6e5b.png)
![Screenshot 2023-03-16 211954](https://user-images.githubusercontent.com/127608152/225794764-d1cb6bd7-617d-47e5-a03f-12f7a14325c8.png)

**Comment by SociallyIneptWeeb** [comment]
You might have to ensure that you have properly copied over .env.sample to .env and made changes to the .env file instead of the .env.sample. Ensure that your file explorer is not hiding file extensions
