### ISSUE TITLE
Cant Recognice my Voice & Subtitler always blank

### ISSUE THREAD

**Issue by SuperSCNova** [SociallyIneptWeeb/LanguageLeapAI#80]
Hey, im running everything in Docker Desktop on my Computer with an RTX4080.
the problem is everytime i speak something it outputs always "Thank you" instead of what i said eg. "How are you"

EDIT:
Forgot to mention that im useing GoogleTranslate instead of the DeepL

CMD
![11](https://user-images.githubusercontent.com/28538637/226108013-9f21266e-1a8a-4e76-ade6-6a12b9a3ffe6.PNG)

also the subtitler wont show any text even i have a Japanese video running.

CMD
![12](https://user-images.githubusercontent.com/28538637/226108009-258b86b8-2f65-4956-b2fc-c10449882741.PNG)

Thank you

**Comment by frrrrrits** [comment]
Make sure your audio setup is correct this maybe because, you put the wrong number in the ``.env`` file, just play around with it. and watch that video tutorial setup carefully.

**Comment by SuperSCNova** [comment]
Found out the Problem :D
It was in the VoiceMeeter, there i turned on B1 instead of B2 for the Translation, also since i have multiple soundcards, i chose the wrong one for the mic, my fault.
