### ISSUE TITLE
can't to get a response from voicevox in colab

### ISSUE THREAD

**Issue by 0Xiaohei0** [SociallyIneptWeeb/LanguageLeapAI#9]
I managed to get the project to work. However I can't seem to get a response from voicevox in colab
![image](https://user-images.githubusercontent.com/24196833/224363146-8afa6929-1ec9-4f79-a359-6ef2cf0a8c3a.png)
the additional print statements are added like this:
![image](https://user-images.githubusercontent.com/24196833/224377428-c415a37b-34fa-44d2-9473-0f35ea2ad3a6.png)

I tired adding the port number to the URL and got a connection refused error
![image](https://user-images.githubusercontent.com/24196833/224377270-738feee1-52dd-4503-befb-469ae168acc3.png)

I ended up hosting voicevox on me local machine and it works.
![image](https://user-images.githubusercontent.com/24196833/224375577-b45637ca-137a-4838-bcde-7ebad6e6d309.png)
Is this due to the Antivirus Web Protection you mentioned?
If so how do I should I configure my firewall? I tried to allow inbound connections like this but the error stays the same:
![image](https://user-images.githubusercontent.com/24196833/224379291-a2b28b3c-300c-464f-bec6-b14278938110.png)

**Comment by OrlandoMR** [comment]
I find the problem, check this:

![imagen](https://user-images.githubusercontent.com/73142446/224449540-e51633b3-d8f6-4f96-8569-29cdb4e17417.png)

Basically the localtunnel is down.

**Comment by SociallyIneptWeeb** [comment]
It should still be working, I believe it's your firewall that's blocking requests from local tunnel's public IP address

**Comment by OrlandoMR** [comment]
I disabled completely the firewall and the error persists so I tried to move the logic to Ngrok to try to fix it.

Doing the above made great progress discovering that the requirements don't install properly if you want you can remove the "-q" after "requirements.txt" after modifying that I got the following error when trying to access the "/" path:

![imagen](https://user-images.githubusercontent.com/73142446/224462571-fa184f58-292f-405e-a4cb-32d791831d3e.png)

If you want, i can provide the code for test it.

**Comment by SociallyIneptWeeb** [comment]
Oh I think voicevox requires python version >= "3.8.1" and python_version < "3.9". I will see if I can update the notebook to use these python versions instead

**Comment by OrlandoMR** [comment]
Oh thank i also will investigate.

**Comment by SociallyIneptWeeb** [comment]
It's because of this [requirements.txt](https://github.com/VOICEVOX/voicevox_engine/blob/master/requirements.txt) file from voicevox which limits the python version, so all of the dependencies are ignored. So I think I might just add some ugly code to manually install these packages, unless theres a way to force pip to force install them regardless of python version

**Comment by SociallyIneptWeeb** [comment]
I just fixed it in a new commit so voicevox should work in colab now
